apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gitscrum
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitscrum
  template:
    metadata:
      labels:
        name: gitscrum
    spec:   
      containers:
      - name: gitscrum
        image: soxueren/gitscrum:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - name: gitscrum-default
          containerPort: 9000
        volumeMounts:
        - name: gitscrum-config
          mountPath: /usr/local/etc/
      - name: mysql-gitscrum
        image: mysql
        env:
         - name: "MYSQL_ROOT_PASSWORD"
           value: "402@sjgs"
         - name: "MYSQL_USER"
           value: "gitscrum"
         - name: "MYSQL_PASSWORD"
           value: "123456"
         - name: "MYSQL_DATABASE"
           value: "develop"           
        volumeMounts:
        - name: default-mysql
          mountPath: /var/lib/mysql  
      imagePullSecrets:
      - name: private-registry-key
      volumes:
      - name: gitscrum-config
        configMap:
          name: gitscrum-config
          items:
          - key: php-fpm.conf
            path: php-fpm.conf
          - key: php.ini
            path: /usr/local/etc/php/php.ini
      - name: default-mysql
        persistentVolumeClaim:
          claimName: mysql-gitscrum-pvc
