apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gitscrum
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitscrum
  template:
    metadata:
      labels:
        name: gitscrum
    spec:   
      containers:
      - name: phpfpm-gitscrum
        image: soxueren/gitscrum:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - name: gitscrum-default
          containerPort: 9000
        env:
         - name: "DB_CONNECTION"
           value: "mysql"          
         - name: "DB_HOST"
           value: "localhost"
         - name: "DB_PORT"
           value: "3306"
         - name: "DB_DATABASE"
           value: "develop"
         - name: "DB_USERNAME"
           value: "gitscrum"
         - name: "DB_PASSWORD"
           value: "123456"
        volumeMounts:
        - name: gitscrum-config
          mountPath: /usr/local/etc/
      - name: nginx-gitscrum
        image: nginx
        imagePullPolicy: IfNotPresent 
        ports:
        - name: nginx-default
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/
      - name: mysql-gitscrum
        image: mysql
        env:
         - name: "MYSQL_ROOT_PASSWORD"
           value: "123456"
         - name: "MYSQL_USER"
           value: "gitscrum"
         - name: "MYSQL_PASSWORD"
           value: "123456"
         - name: "MYSQL_DATABASE"
           value: "develop"           
        volumeMounts:
        - name: default-mysql
          mountPath: /var/lib/mysql  
      imagePullSecrets:
      - name: private-registry-key
      volumes:
      - name: gitscrum-config
        configMap:
          name: gitscrum-config
          items:
          - key: php-fpm.conf
            path: php-fpm.conf
          - key: php.ini
            path: php.ini
      - name: gitscrum-config
        configMap:
          name: nginx-gitscrum-config
          items:
          - key: server.conf
            path: default.conf
      - name: default-mysql
        persistentVolumeClaim:
          claimName: mysql-gitscrum-pvc
